# Generated by Django 5.0.1 on 2024-02-01 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('adress_id', models.AutoField(primary_key=True, serialize=False)),
                ('adress_name', models.CharField(max_length=250)),
                ('adress_lastname', models.CharField(blank=True, max_length=250)),
                ('adress_state', models.CharField(max_length=100)),
                ('adress_house', models.TextField()),
                ('adress_area', models.TextField()),
                ('adress_city', models.CharField(max_length=200)),
                ('adress_phone', models.CharField(max_length=200)),
                ('adress_pincode', models.IntegerField()),
                ('adress_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
