# Generated by Django 5.0.1 on 2024-03-04 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0002_remove_adress_adress_email_adress_adress_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adress',
            unique_together={('adress_phone', 'adress_pincode', 'adress_user')},
        ),
    ]
