# Generated by Django 5.0.1 on 2024-02-19 09:56

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_category_product_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=200)),
                ('coupon_code', models.CharField(default=uuid.uuid4, max_length=16, unique=True)),
                ('coupon_discount', models.FloatField()),
                ('coupon_from', models.DateTimeField()),
                ('coupon_to', models.DateTimeField()),
                ('coupon_min_amount', models.FloatField(default=1)),
                ('coupon_maxuse', models.FloatField(default=1)),
                ('active', models.BooleanField()),
                ('user', models.ManyToManyField(related_name='coupon_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
