# Generated by Django 5.0.1 on 2024-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_category_product_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=200)),
                ('coupen_code', models.CharField(max_length=200)),
                ('coupen_discount', models.FloatField()),
                ('coupen_from', models.DateField()),
                ('coupen_to', models.DateField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
