# Generated by Django 5.0.1 on 2024-02-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupen_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupen_to',
            field=models.DateTimeField(),
        ),
    ]
