# Generated by Django 5.0.1 on 2024-02-14 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0005_alter_coupon_coupen_from_alter_coupon_coupen_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupen_maxuse',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupen_min_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupen_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
