# Generated by Django 5.0.1 on 2024-02-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_coupon_coupen_maxuse_coupon_coupen_min_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
    ]
