# Generated by Django 5.0.1 on 2024-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0008_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product',
            name='size',
            field=models.IntegerField(default=None),
        ),
    ]
